using System.Text;
using System.Text.RegularExpressions;
using War3Net.CodeAnalysis.Jass;
using Wc3MapEngine.Core.Jass;

namespace Wc3MapEngine.Core.Scripts;

/// <summary>
/// Defines the verified script ownership boundary for the map builder. The
/// MCP owns the JASS entry point; GUI/custom-text members remain preserved
/// opaque data and are not regenerated by this pipeline.
/// </summary>
public static class ScriptOwnership
{
    public const string Strategy = "mcp_owned_jass";
    public const string Version = "2.1";
    public const int MaxSourceBytes = 16 * 1024 * 1024;

    private static readonly Regex TriggerString = new(
        @"STRING\s+(?<id>\d+)\s*\{(?<value>[\s\S]*?)\}",
        RegexOptions.Compiled | RegexOptions.CultureInvariant);

    private static readonly Regex JassMain = new(
        @"\bfunction\s+main\s+takes\s+nothing\s+returns\s+nothing\b",
        RegexOptions.Compiled | RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

    private static readonly Regex JassConfig = new(
        @"\bfunction\s+config\s+takes\s+nothing\s+returns\s+nothing\b",
        RegexOptions.Compiled | RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

    private static readonly Regex LuaMain = new(
        @"\bfunction\s+main\s*\(",
        RegexOptions.Compiled | RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

    public static IReadOnlyDictionary<string, string> ParseTriggerStrings(byte[] bytes)
    {
        var text = Encoding.UTF8.GetString(bytes);
        var values = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (Match match in TriggerString.Matches(text))
        {
            var token = $"TRIGSTR_{match.Groups["id"].Value.PadLeft(3, '0')}";
            if (!values.TryAdd(token, match.Groups["value"].Value.Trim()))
            {
                throw new InvalidDataException($"Duplicate trigger string '{token}'.");
            }
        }

        var starts = Regex.Matches(text, @"\bSTRING\s+\d+\s*\{", RegexOptions.CultureInvariant).Count;
        if (starts != values.Count)
        {
            throw new InvalidDataException("One or more trigger-string blocks are malformed or unterminated.");
        }

        return values;
    }

    public static bool HasEntryPoint(string archivePath, byte[] bytes)
    {
        var text = Encoding.UTF8.GetString(bytes);
        return archivePath.EndsWith(".lua", StringComparison.OrdinalIgnoreCase)
            ? LuaMain.IsMatch(text)
            : JassMain.IsMatch(text);
    }

    public static void ValidateMcpOwnedJass(string archivePath, string source)
    {
        if (!archivePath.Equals("war3map.j", StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidDataException("MCP-owned gameplay source must replace the map's war3map.j JASS entry point.");
        }

        if (string.IsNullOrWhiteSpace(source))
        {
            throw new InvalidDataException("MCP-owned JASS source cannot be empty.");
        }

        var bytes = Encoding.UTF8.GetBytes(source);
        if (bytes.Length > MaxSourceBytes)
        {
            throw new InvalidDataException($"MCP-owned JASS source exceeds the {MaxSourceBytes} byte safety limit.");
        }

        if (!HasEntryPoint(archivePath, bytes))
        {
            throw new InvalidDataException("MCP-owned JASS source must contain a recognizable function main takes nothing returns nothing entry point.");
        }

        try
        {
            var compilationUnit = JassSyntaxFactory.ParseCompilationUnit(source);
            _ = compilationUnit;
            var mainFunctions = Regex.Matches(source, @"(?im)^\s*function\s+main\s+takes\s+nothing\s+returns\s+nothing\b");
            if (mainFunctions.Count != 1)
            {
                throw new InvalidDataException($"MCP-owned JASS source must declare exactly one main function; found {mainFunctions.Count}.");
            }

            var configFunctions = Regex.Matches(source, @"(?im)^\s*function\s+config\s+takes\s+nothing\s+returns\s+nothing\b");
            if (configFunctions.Count != 1 || !JassConfig.IsMatch(source))
            {
                throw new InvalidDataException($"MCP-owned JASS source must declare exactly one config function for Warcraft III lobby setup; found {configFunctions.Count}.");
            }

            var apiValidation = new JassValidationService(JassApiRepository.Default).ValidateSource(source);
            if (!apiValidation.IsValid)
            {
                throw new InvalidDataException(JassValidationFailure.Format(apiValidation));
            }
        }
        catch (InvalidDataException)
        {
            throw;
        }
        catch (Exception exception)
        {
            throw new InvalidDataException($"JASS static parse failed: {exception.Message}", exception);
        }
    }

    public static string DescribeLanguage(string archivePath)
        => archivePath.EndsWith(".lua", StringComparison.OrdinalIgnoreCase) ? "Lua" : "Jass";
}
