// Generated by wc3-map-mcp; do not edit in World Editor.
// profile: mvp_2arena
// composer: mcp-jass-composer-2.4
globals
    integer HTW_Round
    integer HTW_Wave
    integer HTW_Phase
    integer HTW_TeamCount
    integer array HTW_TeamMemberA
    integer array HTW_TeamMemberB
    integer array HTW_TeamForce
    string array HTW_TeamStableId
    string array HTW_TeamArena
    boolean array HTW_TeamLiving
    integer array HTW_TeamDestination
    integer HTW_ActivePlayerCount
    integer HTW_ArenaCount
    rect array HTW_ArenaRect
    rect HTW_ArenaRectA
    rect HTW_ArenaRectB
    integer HTW_LivingTeamCount
    integer array HTW_LivingTeamIds
    integer HTW_RouteOffset
    integer HTW_RouteDestinationTeam
    boolean HTW_RoutingLocked
    integer HTW_AdditionalWipeCost
    integer HTW_AliveHeroCount
    integer array HTW_ArenaCreepCount
    group array HTW_ArenaCreepGroup
    boolean HTW_Bootstrapped
    group HTW_CleanupGroup
    integer HTW_CombatSeconds
    timer HTW_CombatTimer
    boolean array HTW_HeroAliveByPlayer
    boolean array HTW_HeroDeathAccountedByPlayer
    boolean array HTW_HeroSelectedByPlayer
    unit HTW_HeroSelectionBuilding
    boolean HTW_HeroSelectionComplete
    integer HTW_HeroSelectionSeconds
    timer HTW_HeroSelectionTimer
    trigger HTW_HeroSelectionTrigger
    integer array HTW_HeroTypeByPlayer
    unit array HTW_HeroUnitByPlayer
    integer HTW_InterestGold
    integer HTW_LastResolvedWave
    boolean HTW_MatchOver
    integer array HTW_PlayerGold
    integer array HTW_PlayerQueueDestination
    integer array HTW_PlayerQueueRemaining
    integer array HTW_PlayerQueueUnitType
    integer HTW_PreparationSeconds
    timer HTW_PreparationTimer
    boolean HTW_ResolutionApplied
    integer HTW_SendCursor
    timer HTW_SendTimer
    integer HTW_SingleDeathCost
    integer HTW_StartingLives
    integer array HTW_TeamDeathsThisWave
    integer array HTW_TeamLives
    integer HTW_TerminalState
    boolean HTW_TransitionGuard
    unit array HTW_WarCampByPlayer
    boolean HTW_WaveActive
    integer HTW_WaveReward
    region HTW_Region_region_0
    region HTW_Region_region_1
    region HTW_Region_region_2
    region HTW_Region_region_3
    region HTW_Region_region_4
    region HTW_Region_region_5
    region HTW_Region_region_6
    region HTW_Region_region_7
    region HTW_Region_region_8
    region HTW_Region_region_9
    real HTW_Event_round_start
    real HTW_Event_wave_resolved
endglobals

function HTW_Regions_InitializeProfile takes nothing returns nothing
    set HTW_ArenaCount = 2
    set HTW_ArenaRect[1] = Rect(1152., -3072., 2496., -448.)
    set HTW_ArenaRect[2] = Rect(-2464., -64., -320., 2240.)
    set HTW_ArenaRectA = HTW_ArenaRect[1]
    set HTW_ArenaRectB = HTW_ArenaRect[2]
endfunction

function HTW_Teams_ConfigureProfile takes nothing returns nothing
    set HTW_TeamCount = 2
    set HTW_LivingTeamCount = 2
    set HTW_ActivePlayerCount = 4
    set HTW_TeamStableId[1] = "team_1"
    set HTW_TeamMemberA[1] = 1
    set HTW_TeamMemberB[1] = 2
    set HTW_TeamForce[1] = 1
    set HTW_TeamArena[1] = "arena_a"
    set HTW_TeamLiving[1] = true
    set HTW_LivingTeamIds[1] = 1
    set HTW_TeamStableId[2] = "team_2"
    set HTW_TeamMemberA[2] = 3
    set HTW_TeamMemberB[2] = 4
    set HTW_TeamForce[2] = 2
    set HTW_TeamArena[2] = "arena_b"
    set HTW_TeamLiving[2] = true
    set HTW_LivingTeamIds[2] = 2
endfunction

// MCP function: HTW_Tuning_Load (module: config.tuning; config/tuning.j)
function HTW_Tuning_Load takes nothing returns nothing
    // Centralized MVP tuning.  These values are intentionally source-owned
    // so a transaction changes one place and the generated map script stays
    // reproducible.
    set HTW_StartingLives = 15
    set HTW_SingleDeathCost = 1
    set HTW_AdditionalWipeCost = 2
    set HTW_PreparationSeconds = 35
    set HTW_CombatSeconds = 90
    set HTW_WaveReward = 50
    set HTW_InterestGold = 10
    set HTW_HeroSelectionSeconds = 60
endfunction

// MCP function: HTW_Objects_Initialize (module: config.objects; config/objects.j)
function HTW_Objects_Initialize takes nothing returns nothing
    // Standard object rawcodes used by the MCP-native MVP.  Custom object
    // definitions remain an independent typed map-component concern.
    // hfoo is the deterministic neutral-hostile base creep, Hpal is the
    // placeholder hero, and hhou is the visible personal War Camp marker.
endfunction

// MCP function: HTW_Regions_Initialize (module: config.regions; config/regions.j)
function HTW_Regions_Initialize takes nothing returns nothing
    // The composer emits this profile-specific registry from typed region
    // data. MVP and six-team profiles therefore share one runtime path.
    call HTW_Regions_InitializeProfile()
endfunction

// MCP function: HTW_Teams_Initialize (module: config.teams; config/teams.j)
function HTW_Teams_Initialize takes nothing returns nothing
    local integer teamIndex
    call HTW_Teams_ConfigureProfile()
    set teamIndex = 1
    loop
        exitwhen teamIndex > HTW_TeamCount
        set HTW_TeamLives[teamIndex] = HTW_StartingLives
        set teamIndex = teamIndex + 1
    endloop
endfunction

// MCP function: HTW_Teams_FindByPlayer (module: config.teams; config/teams.j)
function HTW_Teams_FindByPlayer takes integer playerId returns integer
    local integer teamIndex
    set teamIndex = 1
    loop
        exitwhen teamIndex > HTW_TeamCount
        if HTW_TeamMemberA[teamIndex] == playerId or HTW_TeamMemberB[teamIndex] == playerId then
            return teamIndex
        endif
        set teamIndex = teamIndex + 1
    endloop
    return 0
endfunction

// MCP function: HTW_State_Reset (module: core.state; core/state.j)
function HTW_State_Reset takes nothing returns nothing
    local integer index
    set HTW_Round = 1
    set HTW_Wave = 0
    set HTW_Phase = 0
    set HTW_RoutingLocked = false
    set HTW_TransitionGuard = false
    set HTW_WaveActive = false
    set HTW_ResolutionApplied = false
    set HTW_MatchOver = false
    set HTW_TerminalState = 0
    set HTW_LastResolvedWave = 0
    set HTW_SendCursor = 1
    set HTW_AliveHeroCount = 0
    set HTW_PreparationTimer = null
    set HTW_CombatTimer = null
    set HTW_SendTimer = null
    set HTW_CleanupGroup = null
    set HTW_HeroSelectionBuilding = null
    set HTW_HeroSelectionTrigger = null
    set HTW_HeroSelectionTimer = null
    set HTW_HeroSelectionComplete = false
    set index = 1
    loop
        exitwhen index > 24
        set HTW_HeroUnitByPlayer[index] = null
        set HTW_HeroAliveByPlayer[index] = false
        set HTW_HeroDeathAccountedByPlayer[index] = false
        set HTW_HeroSelectedByPlayer[index] = false
        set HTW_HeroTypeByPlayer[index] = 0
        set HTW_WarCampByPlayer[index] = null
        set HTW_PlayerGold[index] = 0
        set HTW_PlayerQueueUnitType[index] = 0
        set HTW_PlayerQueueRemaining[index] = 0
        set HTW_PlayerQueueDestination[index] = 0
        set index = index + 1
    endloop
    set index = 1
    loop
        exitwhen index > HTW_TeamCount
        set HTW_TeamLives[index] = HTW_StartingLives
        set HTW_TeamDeathsThisWave[index] = 0
        set HTW_ArenaCreepGroup[index] = null
        set HTW_ArenaCreepCount[index] = 0
        set index = index + 1
    endloop
endfunction

// MCP function: HTW_Content_Heroes (module: content.heroes; content/heroes.j)
function HTW_Content_Heroes takes nothing returns nothing
    // V8 keeps the hero roster deliberately small: four custom unit rawcodes
    // inherit their visuals and baseline abilities from standard heroes.  The
    // object definitions live in object-data/v8-hero-objects.json.
endfunction

// MCP function: HTW_Content_HeroTypeForSlot (module: content.heroes; content/heroes.j)
function HTW_Content_HeroTypeForSlot takes integer slot returns integer
    if slot == 1 then
        return 'H001'
    elseif slot == 2 then
        return 'H002'
    elseif slot == 3 then
        return 'H003'
    endif
    return 'H004'
endfunction

// MCP function: HTW_Content_IsHeroType (module: content.heroes; content/heroes.j)
function HTW_Content_IsHeroType takes integer heroType returns boolean
    return heroType == 'H001' or heroType == 'H002' or heroType == 'H003' or heroType == 'H004'
endfunction

// MCP function: HTW_Content_HeroName (module: content.heroes; content/heroes.j)
function HTW_Content_HeroName takes integer heroType returns string
    if heroType == 'H001' then
        return "Guardian"
    elseif heroType == 'H002' then
        return "Striker"
    elseif heroType == 'H003' then
        return "Controller"
    endif
    return "Support"
endfunction

// MCP function: HTW_Content_CreateHero (module: content.heroes; content/heroes.j)
function HTW_Content_CreateHero takes integer playerId, integer heroType, real x, real y returns unit
    return CreateUnit(Player(playerId - 1), heroType, x, y, 270.)
endfunction

// MCP function: HTW_Content_Abilities (module: content.abilities; content/abilities.j)
function HTW_Content_Abilities takes nothing returns nothing
    // Standard placeholder hero abilities are intentionally left unchanged in
    // the MVP.  Custom ability definitions are supplied by typed object data.
endfunction

// MCP function: HTW_Content_RemoveCreep (module: content.base-waves; content/base-waves.j)
function HTW_Content_RemoveCreep takes nothing returns nothing
    if GetEnumUnit() != null then
        call RemoveUnit(GetEnumUnit())
    endif
endfunction

// MCP function: HTW_Content_CleanupBaseWaves (module: content.base-waves; content/base-waves.j)
function HTW_Content_CleanupBaseWaves takes nothing returns nothing
    local integer arenaIndex
    set arenaIndex = 1
    loop
        exitwhen arenaIndex > HTW_ArenaCount
        if HTW_ArenaCreepGroup[arenaIndex] != null then
            set HTW_CleanupGroup = HTW_ArenaCreepGroup[arenaIndex]
            call ForGroup(HTW_CleanupGroup, function HTW_Content_RemoveCreep)
            call DestroyGroup(HTW_CleanupGroup)
            set HTW_ArenaCreepGroup[arenaIndex] = null
            set HTW_ArenaCreepCount[arenaIndex] = 0
        endif
        set arenaIndex = arenaIndex + 1
    endloop
endfunction

// MCP function: HTW_Economy_GrantPersonalGold (module: systems.economy; systems/economy.j)
function HTW_Economy_GrantPersonalGold takes nothing returns nothing
    local integer playerId
    local integer teamIndex
    set playerId = 1
    loop
        exitwhen playerId > HTW_ActivePlayerCount
        set teamIndex = HTW_Teams_FindByPlayer(playerId)
        if teamIndex > 0 and HTW_TeamLiving[teamIndex] then
            set HTW_PlayerGold[playerId] = HTW_PlayerGold[playerId] + HTW_WaveReward + HTW_InterestGold
        endif
        set playerId = playerId + 1
    endloop
endfunction

// MCP function: HTW_Economy_GetGold (module: systems.economy; systems/economy.j)
function HTW_Economy_GetGold takes integer playerId returns integer
    if playerId < 1 or playerId > 24 then
        return 0
    endif
    return HTW_PlayerGold[playerId]
endfunction

// MCP function: HTW_Content_Items (module: content.items; content/items.j)
function HTW_Content_Items takes nothing returns nothing
    // Item catalog hook.  Purchase records are player-owned and are handled
    // by systems.economy; no shared team wallet is introduced here.
endfunction

// MCP function: HTW_Content_SendUnits (module: content.send-units; content/send-units.j)
function HTW_Content_SendUnits takes nothing returns nothing
    // The sender passes the selected type and destination to this narrow
    // content boundary; no map structure is mutated here.
endfunction

// MCP function: HTW_Content_SendOne (module: content.send-units; content/send-units.j)
function HTW_Content_SendOne takes integer unitType, integer destinationTeam returns unit
    local real x
    local real y
    set x = GetRectCenterX(HTW_ArenaRect[destinationTeam])
    set y = GetRectCenterY(HTW_ArenaRect[destinationTeam])
    return CreateUnit(Player(PLAYER_NEUTRAL_AGGRESSIVE), unitType, x, y, 270.)
endfunction

// MCP function: HTW_Debug_LogText (module: core.debug; core/debug.j)
function HTW_Debug_LogText takes string message returns nothing
    call DisplayTextToForce(GetPlayersAll(), "[HTW] chunk=HTW-05 round=" + I2S(HTW_Round) + " wave=" + I2S(HTW_Wave) + " phase=" + I2S(HTW_Phase) + " " + message)
endfunction

// MCP function: HTW_Content_BaseWaves (module: content.base-waves; content/base-waves.j)
function HTW_Content_BaseWaves takes nothing returns nothing
    local integer arenaIndex
    local integer creepIndex
    local real x
    local real y
    local unit creep
    set arenaIndex = 1
    loop
        exitwhen arenaIndex > HTW_ArenaCount
        if HTW_ArenaCreepGroup[arenaIndex] == null then
            set HTW_ArenaCreepGroup[arenaIndex] = CreateGroup()
        endif
        set x = GetRectCenterX(HTW_ArenaRect[arenaIndex])
        set y = GetRectCenterY(HTW_ArenaRect[arenaIndex])
        set creepIndex = 1
        loop
            exitwhen creepIndex > 3
            set creep = CreateUnit(Player(PLAYER_NEUTRAL_AGGRESSIVE), 'hfoo', x + I2R(creepIndex * 48), y + I2R(creepIndex * 32), 270.)
            call GroupAddUnit(HTW_ArenaCreepGroup[arenaIndex], creep)
            set HTW_ArenaCreepCount[arenaIndex] = HTW_ArenaCreepCount[arenaIndex] + 1
            set creepIndex = creepIndex + 1
        endloop
        set arenaIndex = arenaIndex + 1
    endloop
    call HTW_Debug_LogText("base wave spawned")
endfunction

// MCP function: HTW_Economy_Purchase (module: systems.economy; systems/economy.j)
function HTW_Economy_Purchase takes integer playerId, integer unitType, integer quantity, integer cost returns boolean
    local integer teamIndex
    local integer destinationTeam
    if playerId < 1 or playerId > HTW_ActivePlayerCount or quantity <= 0 or cost < 0 or unitType == 0 then
        return false
    endif
    if HTW_Phase != 1 or HTW_MatchOver then
        return false
    endif
    set teamIndex = HTW_Teams_FindByPlayer(playerId)
    if teamIndex == 0 or not HTW_TeamLiving[teamIndex] then
        return false
    endif
    set destinationTeam = HTW_TeamDestination[teamIndex]
    if destinationTeam == 0 or destinationTeam == teamIndex then
        return false
    endif
    if HTW_PlayerGold[playerId] < quantity * cost then
        return false
    endif
    if HTW_PlayerQueueRemaining[playerId] > 0 then
        return false
    endif
    set HTW_PlayerGold[playerId] = HTW_PlayerGold[playerId] - quantity * cost
    set HTW_PlayerQueueUnitType[playerId] = unitType
    set HTW_PlayerQueueRemaining[playerId] = quantity
    set HTW_PlayerQueueDestination[playerId] = destinationTeam
    call HTW_Debug_LogText("personal purchase queued")
    return true
endfunction

// MCP function: HTW_MCP_Bootstrap (module: core.bootstrap; core/bootstrap.j)
function HTW_MCP_Bootstrap takes nothing returns nothing
    if HTW_Bootstrapped then
        return
    endif
    call HTW_Tuning_Load()
    call HTW_Teams_Initialize()
    call HTW_Regions_Initialize()
    call HTW_Objects_Initialize()
    call HTW_State_Reset()
    set HTW_Bootstrapped = true
    call HTW_Debug_LogText("bootstrap complete")
endfunction

// MCP function: HTW_Debug_Log (module: core.debug; core/debug.j)
function HTW_Debug_Log takes nothing returns nothing
    call HTW_Debug_LogText("heartbeat")
endfunction

// MCP function: HTW_Events_Register (module: core.events; core/events.j)
function HTW_Events_Register takes nothing returns nothing
    // The composer owns native trigger registration.  These fire helpers are
    // the single source of custom-event transitions used by runtime systems.
endfunction

// MCP function: HTW_Events_FireRoundStart (module: core.events; core/events.j)
function HTW_Events_FireRoundStart takes nothing returns nothing
    set HTW_Event_round_start = 1.
    set HTW_Event_round_start = 0.
endfunction

// MCP function: HTW_Events_FireWaveResolved (module: core.events; core/events.j)
function HTW_Events_FireWaveResolved takes nothing returns nothing
    set HTW_Event_wave_resolved = 1.
    set HTW_Event_wave_resolved = 0.
endfunction

// MCP function: HTW_Heroes_Initialize (module: systems.heroes; systems/heroes.j)
function HTW_Heroes_Initialize takes nothing returns nothing
    local integer playerId
    local integer teamIndex
    local real x
    local real y
    set playerId = 1
    loop
        exitwhen playerId > HTW_ActivePlayerCount
        set teamIndex = HTW_Teams_FindByPlayer(playerId)
        set x = GetRectCenterX(HTW_ArenaRect[teamIndex])
        set y = GetRectCenterY(HTW_ArenaRect[teamIndex])
        // Hero units are selected at the shared altar before the first wave.
        // Keep the existing War Camp placement unchanged for the MVP shell.
        set HTW_HeroUnitByPlayer[playerId] = null
        set HTW_HeroAliveByPlayer[playerId] = false
        set HTW_HeroDeathAccountedByPlayer[playerId] = false
        set HTW_WarCampByPlayer[playerId] = CreateUnit(Player(playerId - 1), 'hhou', x + I2R(playerId * 96), y - I2R(playerId * 48), 270.)
        set playerId = playerId + 1
    endloop
    call HTW_Debug_LogText("personal War Camps initialized; awaiting shared hero altar selections")
endfunction

// MCP function: HTW_Heroes_IsTracked (module: systems.heroes; systems/heroes.j)
function HTW_Heroes_IsTracked takes unit hero returns boolean
    local integer playerId
    set playerId = 1
    loop
        exitwhen playerId > 24
        if HTW_HeroUnitByPlayer[playerId] == hero then
            return true
        endif
        set playerId = playerId + 1
    endloop
    return false
endfunction

// MCP function: HTW_Heroes_PlayerId (module: systems.heroes; systems/heroes.j)
function HTW_Heroes_PlayerId takes unit hero returns integer
    local integer playerId
    set playerId = 1
    loop
        exitwhen playerId > 24
        if HTW_HeroUnitByPlayer[playerId] == hero then
            return playerId
        endif
        set playerId = playerId + 1
    endloop
    return 0
endfunction

// MCP function: HTW_Heroes_ReviveLiving (module: systems.heroes; systems/heroes.j)
function HTW_Heroes_ReviveLiving takes nothing returns nothing
    local integer playerId
    local integer teamIndex
    local real x
    local real y
    set playerId = 1
    loop
        exitwhen playerId > HTW_ActivePlayerCount
        set teamIndex = HTW_Teams_FindByPlayer(playerId)
        if teamIndex > 0 and HTW_TeamLiving[teamIndex] and not HTW_HeroAliveByPlayer[playerId] then
            set x = GetRectCenterX(HTW_ArenaRect[teamIndex])
            set y = GetRectCenterY(HTW_ArenaRect[teamIndex])
            call ReviveHero(HTW_HeroUnitByPlayer[playerId], x, y, true)
            set HTW_HeroAliveByPlayer[playerId] = true
            set HTW_HeroDeathAccountedByPlayer[playerId] = false
            set HTW_AliveHeroCount = HTW_AliveHeroCount + 1
        endif
        set playerId = playerId + 1
    endloop
endfunction

// MCP function: HTW_Elimination_Recalculate (module: systems.elimination; systems/elimination.j)
function HTW_Elimination_Recalculate takes nothing returns nothing
    local integer teamIndex
    set HTW_LivingTeamCount = 0
    set teamIndex = 1
    loop
        exitwhen teamIndex > HTW_TeamCount
        if HTW_TeamLiving[teamIndex] then
            set HTW_LivingTeamCount = HTW_LivingTeamCount + 1
            set HTW_LivingTeamIds[HTW_LivingTeamCount] = teamIndex
        endif
        set teamIndex = teamIndex + 1
    endloop
    if HTW_LivingTeamCount == 0 then
        set HTW_TerminalState = 2
        set HTW_MatchOver = true
        set HTW_Phase = 5
        call HTW_Debug_LogText("draw: no living teams")
    elseif HTW_LivingTeamCount == 1 then
        set HTW_TerminalState = 1
        set HTW_MatchOver = true
        set HTW_Phase = 4
        call HTW_Debug_LogText("victory: one living team")
    endif
endfunction

// MCP function: HTW_Lives_AccountDeath (module: systems.lives; systems/lives.j)
function HTW_Lives_AccountDeath takes nothing returns nothing
    local unit deadHero
    local integer playerId
    local integer teamIndex
    set deadHero = GetTriggerUnit()
    set playerId = HTW_Heroes_PlayerId(deadHero)
    if playerId == 0 or HTW_HeroDeathAccountedByPlayer[playerId] then
        set deadHero = null
        return
    endif
    set HTW_HeroDeathAccountedByPlayer[playerId] = true
    set HTW_HeroAliveByPlayer[playerId] = false
    set HTW_AliveHeroCount = HTW_AliveHeroCount - 1
    set teamIndex = HTW_Teams_FindByPlayer(playerId)
    if teamIndex > 0 and HTW_TeamLiving[teamIndex] then
        set HTW_TeamDeathsThisWave[teamIndex] = HTW_TeamDeathsThisWave[teamIndex] + 1
        if HTW_TeamDeathsThisWave[teamIndex] == 1 then
            set HTW_TeamLives[teamIndex] = HTW_TeamLives[teamIndex] - HTW_SingleDeathCost
        else
            // The second hero death costs two additional lives, making a
            // two-hero wipe exactly three lives for this wave.
            set HTW_TeamLives[teamIndex] = HTW_TeamLives[teamIndex] - HTW_AdditionalWipeCost
        endif
        if HTW_TeamLives[teamIndex] <= 0 then
            set HTW_TeamLiving[teamIndex] = false
            call HTW_Elimination_Recalculate()
        endif
    endif
    call HTW_Debug_LogText("hero death accounted once")
    set deadHero = null
endfunction

// MCP function: HTW_Heroes_OnDeath (module: systems.heroes; systems/heroes.j)
function HTW_Heroes_OnDeath takes nothing returns nothing
    local unit deadHero
    set deadHero = GetTriggerUnit()
    if HTW_Heroes_IsTracked(deadHero) then
        call HTW_Lives_AccountDeath()
    endif
    set deadHero = null
endfunction

// MCP function: HTW_Routing_Compute (module: systems.routing; systems/routing.j)
function HTW_Routing_Compute takes nothing returns nothing
    local integer teamIndex
    local integer livingIndex
    if HTW_RoutingLocked then
        return
    endif
    set HTW_RouteOffset = 0
    set HTW_RouteDestinationTeam = 0
    if HTW_LivingTeamCount < 2 then
        return
    endif
    set HTW_RouteOffset = 1 + ModuloInteger(HTW_Round - 1, HTW_LivingTeamCount - 1)
    set teamIndex = 1
    loop
        exitwhen teamIndex > HTW_TeamCount
        set HTW_TeamDestination[teamIndex] = 0
        if HTW_TeamLiving[teamIndex] then
            set livingIndex = 1
            loop
                exitwhen livingIndex > HTW_LivingTeamCount
                if HTW_LivingTeamIds[livingIndex] == teamIndex then
                    set HTW_TeamDestination[teamIndex] = HTW_LivingTeamIds[ModuloInteger(livingIndex - 1 + HTW_RouteOffset, HTW_LivingTeamCount) + 1]
                    set livingIndex = HTW_LivingTeamCount
                endif
                set livingIndex = livingIndex + 1
            endloop
        endif
        set teamIndex = teamIndex + 1
    endloop
    set HTW_RouteDestinationTeam = HTW_TeamDestination[1]
    set HTW_RoutingLocked = true
endfunction

// MCP function: HTW_Waves_Resolve (module: systems.waves; systems/waves.j)
function HTW_Waves_Resolve takes nothing returns nothing
    if not HTW_WaveActive or HTW_ResolutionApplied then
        return
    endif
    set HTW_ResolutionApplied = true
    call HTW_Content_CleanupBaseWaves()
    call HTW_Heroes_ReviveLiving()
    call HTW_Economy_GrantPersonalGold()
    set HTW_WaveActive = false
    set HTW_LastResolvedWave = HTW_Wave
    if HTW_PreparationTimer != null then
        call PauseTimer(HTW_PreparationTimer)
    endif
    if HTW_CombatTimer != null then
        call PauseTimer(HTW_CombatTimer)
    endif
    call HTW_Elimination_Recalculate()
    if not HTW_MatchOver then
        set HTW_Round = HTW_Round + 1
        call HTW_Events_FireWaveResolved()
    endif
    call HTW_Debug_LogText("wave resolved exactly once")
endfunction

// MCP function: HTW_Phases_BeginResolution (module: systems.phases; systems/phases.j)
function HTW_Phases_BeginResolution takes nothing returns nothing
    // A terminal result may be reached during combat. The active wave still
    // needs one guarded cleanup pass before the match stops accepting work.
    if HTW_Phase != 2 or HTW_TransitionGuard then
        return
    endif
    set HTW_TransitionGuard = true
    set HTW_Phase = 3
    set HTW_TransitionGuard = false
    call HTW_Waves_Resolve()
endfunction

// MCP function: HTW_Phases_BeginCombat (module: systems.phases; systems/phases.j)
function HTW_Phases_BeginCombat takes nothing returns nothing
    if HTW_MatchOver or HTW_Phase != 1 or HTW_TransitionGuard then
        return
    endif
    set HTW_TransitionGuard = true
    set HTW_Phase = 2
    if HTW_CombatTimer == null then
        set HTW_CombatTimer = CreateTimer()
    endif
    call TimerStart(HTW_CombatTimer, I2R(HTW_CombatSeconds), false, function HTW_Phases_BeginResolution)
    call HTW_Debug_LogText("phase preparation -> combat")
    set HTW_TransitionGuard = false
endfunction

// MCP function: HTW_Phases_Advance (module: systems.phases; systems/phases.j)
function HTW_Phases_Advance takes nothing returns nothing
    if HTW_MatchOver or HTW_TransitionGuard then
        return
    endif
    if HTW_Phase == 1 then
        call HTW_Phases_BeginCombat()
    elseif HTW_Phase == 2 then
        call HTW_Phases_BeginResolution()
    endif
endfunction

// MCP function: HTW_Phases_Tick (module: systems.phases; systems/phases.j)
function HTW_Phases_Tick takes nothing returns nothing
    if HTW_MatchOver and not (HTW_WaveActive and HTW_Phase == 2) then
        return
    endif
    if HTW_Phase == 1 and HTW_PreparationTimer != null and TimerGetRemaining(HTW_PreparationTimer) <= 0. then
        call HTW_Phases_BeginCombat()
    elseif HTW_Phase == 2 and HTW_CombatTimer != null and TimerGetRemaining(HTW_CombatTimer) <= 0. then
        call HTW_Phases_BeginResolution()
    endif
endfunction

// MCP function: HTW_Waves_Prepare (module: systems.waves; systems/waves.j)
function HTW_Waves_Prepare takes nothing returns nothing
    if HTW_MatchOver then
        return
    endif
    if HTW_WaveActive then
        return
    endif
    if HTW_Round < 1 then
        set HTW_Round = 1
    endif
    call HTW_Elimination_Recalculate()
    if HTW_MatchOver then
        return
    endif
    set HTW_Phase = 1
    set HTW_Wave = HTW_Wave + 1
    set HTW_RoutingLocked = false
    call HTW_Routing_Compute()
    set HTW_WaveActive = true
    set HTW_ResolutionApplied = false
    set HTW_TeamDeathsThisWave[1] = 0
    set HTW_TeamDeathsThisWave[2] = 0
    set HTW_TeamDeathsThisWave[3] = 0
    set HTW_TeamDeathsThisWave[4] = 0
    set HTW_TeamDeathsThisWave[5] = 0
    set HTW_TeamDeathsThisWave[6] = 0
    call HTW_Content_BaseWaves()
    if HTW_PreparationTimer == null then
        set HTW_PreparationTimer = CreateTimer()
    endif
    call TimerStart(HTW_PreparationTimer, I2R(HTW_PreparationSeconds), false, function HTW_Phases_BeginCombat)
    call HTW_Events_FireRoundStart()
    call HTW_Debug_LogText("new wave prepared")
endfunction

// MCP function: HTW_HeroSelection_RefillStock (module: systems.hero-selection; systems/hero-selection.j)
function HTW_HeroSelection_RefillStock takes nothing returns nothing
    if HTW_HeroSelectionBuilding == null then
        return
    endif
    call SetUnitStock(HTW_HeroSelectionBuilding, HTW_Content_HeroTypeForSlot(1), 1)
    call SetUnitStock(HTW_HeroSelectionBuilding, HTW_Content_HeroTypeForSlot(2), 1)
    call SetUnitStock(HTW_HeroSelectionBuilding, HTW_Content_HeroTypeForSlot(3), 1)
    call SetUnitStock(HTW_HeroSelectionBuilding, HTW_Content_HeroTypeForSlot(4), 1)
endfunction

// MCP function: HTW_HeroSelection_PlayerHasTeammateHero (module: systems.hero-selection; systems/hero-selection.j)
function HTW_HeroSelection_PlayerHasTeammateHero takes integer playerId, integer heroType returns boolean
    local integer teamIndex
    local integer teammateId
    set teamIndex = HTW_Teams_FindByPlayer(playerId)
    if teamIndex <= 0 then
        return true
    endif
    set teammateId = HTW_TeamMemberA[teamIndex]
    if teammateId == playerId then
        set teammateId = HTW_TeamMemberB[teamIndex]
    endif
    return teammateId > 0 and HTW_HeroSelectedByPlayer[teammateId] and HTW_HeroTypeByPlayer[teammateId] == heroType
endfunction

// MCP function: HTW_HeroSelection_DeployHero (module: systems.hero-selection; systems/hero-selection.j)
function HTW_HeroSelection_DeployHero takes integer playerId returns nothing
    local integer teamIndex
    local real x
    local real y
    set teamIndex = HTW_Teams_FindByPlayer(playerId)
    if teamIndex <= 0 or HTW_HeroUnitByPlayer[playerId] == null then
        return
    endif
    set x = GetRectCenterX(HTW_ArenaRect[teamIndex])
    set y = GetRectCenterY(HTW_ArenaRect[teamIndex])
    call SetUnitPosition(HTW_HeroUnitByPlayer[playerId], x + I2R(playerId * 64), y + I2R(playerId * 48))
    set HTW_HeroAliveByPlayer[playerId] = true
    set HTW_HeroDeathAccountedByPlayer[playerId] = false
    set HTW_AliveHeroCount = HTW_AliveHeroCount + 1
endfunction

// MCP function: HTW_HeroSelection_Complete (module: systems.hero-selection; systems/hero-selection.j)
function HTW_HeroSelection_Complete takes nothing returns nothing
    local integer playerId
    if HTW_HeroSelectionComplete then
        return
    endif
    set HTW_HeroSelectionComplete = true
    if HTW_HeroSelectionTimer != null then
        call PauseTimer(HTW_HeroSelectionTimer)
        call DestroyTimer(HTW_HeroSelectionTimer)
        set HTW_HeroSelectionTimer = null
    endif
    if HTW_HeroSelectionBuilding != null then
        call RemoveUnit(HTW_HeroSelectionBuilding)
        set HTW_HeroSelectionBuilding = null
    endif
    set playerId = 1
    loop
        exitwhen playerId > HTW_ActivePlayerCount
        call HTW_HeroSelection_DeployHero(playerId)
        set playerId = playerId + 1
    endloop
    set HTW_Phase = 1
    call HTW_Debug_LogText("hero selection complete; first preparation phase started")
    call HTW_Waves_Prepare()
endfunction

// MCP function: HTW_HeroSelection_SelectForPlayer (module: systems.hero-selection; systems/hero-selection.j)
function HTW_HeroSelection_SelectForPlayer takes integer playerId, integer heroType returns boolean
    if playerId < 1 or playerId > HTW_ActivePlayerCount or not HTW_Content_IsHeroType(heroType) then
        return false
    endif
    if HTW_HeroSelectedByPlayer[playerId] or HTW_HeroSelection_PlayerHasTeammateHero(playerId, heroType) then
        return false
    endif
    set HTW_HeroSelectedByPlayer[playerId] = true
    set HTW_HeroTypeByPlayer[playerId] = heroType
    set HTW_HeroUnitByPlayer[playerId] = HTW_Content_CreateHero(playerId, heroType, 216., -336.)
    call DisplayTextToPlayer(Player(playerId - 1), 0., 0., "Selected " + HTW_Content_HeroName(heroType) + ".")
    return true
endfunction

// MCP function: HTW_HeroSelection_AllPlayersReady (module: systems.hero-selection; systems/hero-selection.j)
function HTW_HeroSelection_AllPlayersReady takes nothing returns boolean
    local integer playerId
    set playerId = 1
    loop
        exitwhen playerId > HTW_ActivePlayerCount
        if not HTW_HeroSelectedByPlayer[playerId] then
            return false
        endif
        set playerId = playerId + 1
    endloop
    return true
endfunction

// MCP function: HTW_HeroSelection_OnSell (module: systems.hero-selection; systems/hero-selection.j)
function HTW_HeroSelection_OnSell takes nothing returns nothing
    local unit soldHero
    local integer playerId
    local integer heroType
    set soldHero = GetSoldUnit()
    set playerId = GetPlayerId(GetOwningPlayer(soldHero)) + 1
    set heroType = GetUnitTypeId(soldHero)
    if not HTW_HeroSelection_SelectForPlayer(playerId, heroType) then
        call RemoveUnit(soldHero)
        call HTW_HeroSelection_RefillStock()
        call DisplayTextToPlayer(Player(playerId - 1), 0., 0., "That hero is unavailable. Choose another hero.")
        set soldHero = null
        return
    endif
    call HTW_HeroSelection_RefillStock()
    call HTW_Debug_LogText("player " + I2S(playerId) + " selected " + HTW_Content_HeroName(heroType))
    if HTW_HeroSelection_AllPlayersReady() then
        call HTW_HeroSelection_Complete()
    endif
    set soldHero = null
endfunction

// MCP function: HTW_HeroSelection_AutoPick (module: systems.hero-selection; systems/hero-selection.j)
function HTW_HeroSelection_AutoPick takes integer playerId returns nothing
    local integer slot
    local integer heroType
    set slot = 1
    loop
        exitwhen slot > 4
        set heroType = HTW_Content_HeroTypeForSlot(slot)
        if HTW_HeroSelection_SelectForPlayer(playerId, heroType) then
            return
        endif
        set slot = slot + 1
    endloop
endfunction

// MCP function: HTW_HeroSelection_OnTimeout (module: systems.hero-selection; systems/hero-selection.j)
function HTW_HeroSelection_OnTimeout takes nothing returns nothing
    local integer playerId
    set playerId = 1
    loop
        exitwhen playerId > HTW_ActivePlayerCount
        if not HTW_HeroSelectedByPlayer[playerId] then
            call HTW_HeroSelection_AutoPick(playerId)
        endif
        set playerId = playerId + 1
    endloop
    if HTW_HeroSelection_AllPlayersReady() then
        call HTW_HeroSelection_Complete()
    endif
endfunction

// MCP function: HTW_HeroSelection_Begin (module: systems.hero-selection; systems/hero-selection.j)
function HTW_HeroSelection_Begin takes nothing returns nothing
    set HTW_HeroSelectionComplete = false
    set HTW_HeroSelectionBuilding = CreateUnit(Player(PLAYER_NEUTRAL_PASSIVE), 'H0AL', 216., -336., 270.)
    set HTW_HeroSelectionTrigger = CreateTrigger()
    call TriggerRegisterUnitEvent(HTW_HeroSelectionTrigger, HTW_HeroSelectionBuilding, EVENT_UNIT_SELL)
    call TriggerAddAction(HTW_HeroSelectionTrigger, function HTW_HeroSelection_OnSell)
    call HTW_HeroSelection_RefillStock()
    set HTW_HeroSelectionTimer = CreateTimer()
    call TimerStart(HTW_HeroSelectionTimer, I2R(HTW_HeroSelectionSeconds), false, function HTW_HeroSelection_OnTimeout)
    call DisplayTextToPlayer(GetLocalPlayer(), 0., 0., "Choose a hero at the shared HTW Hero Altar.")
    call HTW_Debug_LogText("shared custom Hero Altar created; hero selection is open")
endfunction

// MCP function: HTW_Information_Display (module: systems.information; systems/information.j)
function HTW_Information_Display takes nothing returns nothing
    local integer teamIndex
    local string state
    set state = "running"
    if HTW_TerminalState == 1 then
        set state = "victory"
    elseif HTW_TerminalState == 2 then
        set state = "draw"
    endif
    call DisplayTextToForce(GetPlayersAll(), "[HTW] round=" + I2S(HTW_Round) + " wave=" + I2S(HTW_Wave) + " phase=" + I2S(HTW_Phase) + " state=" + state)
    set teamIndex = 1
    loop
        exitwhen teamIndex > HTW_TeamCount
        if HTW_TeamLiving[teamIndex] then
            call DisplayTextToForce(GetPlayersAll(), "[HTW] team=" + I2S(teamIndex) + " lives=" + I2S(HTW_TeamLives[teamIndex]) + " destination=" + I2S(HTW_TeamDestination[teamIndex]))
        endif
        set teamIndex = teamIndex + 1
    endloop
    call HTW_Debug_LogText("public phase/lives/route information displayed")
endfunction

// MCP function: HTW_Sending_QueueCreep (module: systems.sending; systems/sending.j)
function HTW_Sending_QueueCreep takes integer playerId, integer unitType, integer quantity, integer cost returns boolean
    return HTW_Economy_Purchase(playerId, unitType, quantity, cost)
endfunction

// MCP function: HTW_Sending_ProcessQueues (module: systems.sending; systems/sending.j)
function HTW_Sending_ProcessQueues takes nothing returns nothing
    local integer attempts
    local integer playerId
    local integer destinationTeam
    local unit sent
    if HTW_Phase != 2 or not HTW_WaveActive or HTW_MatchOver then
        return
    endif
    set attempts = 0
    set playerId = HTW_SendCursor
    loop
        exitwhen attempts >= HTW_ActivePlayerCount
        if playerId > HTW_ActivePlayerCount then
            set playerId = 1
        endif
        if HTW_PlayerQueueRemaining[playerId] > 0 then
            set destinationTeam = HTW_PlayerQueueDestination[playerId]
            if destinationTeam != 0 and destinationTeam != HTW_Teams_FindByPlayer(playerId) then
                set sent = HTW_Content_SendOne(HTW_PlayerQueueUnitType[playerId], destinationTeam)
                if sent != null then
                    set HTW_PlayerQueueRemaining[playerId] = HTW_PlayerQueueRemaining[playerId] - 1
                    call HTW_Debug_LogText("staggered send emitted")
                endif
            else
                set HTW_PlayerQueueRemaining[playerId] = 0
            endif
            set HTW_SendCursor = playerId + 1
            set sent = null
            return
        endif
        set playerId = playerId + 1
        set attempts = attempts + 1
    endloop
endfunction

// MCP function: HTW_Sending_Queue (module: systems.sending; systems/sending.j)
function HTW_Sending_Queue takes nothing returns nothing
    call HTW_Sending_ProcessQueues()
endfunction

// MCP function: HTW_Test_Assert (module: tests.assertions; tests/assertions.j)
function HTW_Test_Assert takes nothing returns nothing
    call HTW_Debug_LogText("test assertion hook ready")
endfunction

// MCP function: HTW_Test_AssertBoolean (module: tests.assertions; tests/assertions.j)
function HTW_Test_AssertBoolean takes boolean condition, string label returns nothing
    if condition then
        call HTW_Debug_LogText("scenario=" + label + " result=pass")
    else
        call HTW_Debug_LogText("scenario=" + label + " result=fail")
    endif
endfunction

// MCP function: HTW_OnMapInit (module: tests.scenarios; tests/scenarios.j)
function HTW_OnMapInit takes nothing returns nothing
    call HTW_Debug_LogText("scenario=fresh_initialization expected=phase_preparation")
endfunction

// MCP function: HTW_OnRoundStart (module: tests.scenarios; tests/scenarios.j)
function HTW_OnRoundStart takes nothing returns nothing
    call HTW_Debug_LogText("scenario=preparation_combat_resolution round_start")
endfunction

// MCP function: HTW_OnWaveResolved (module: tests.scenarios; tests/scenarios.j)
function HTW_OnWaveResolved takes nothing returns nothing
    call HTW_Debug_LogText("scenario=wave_resolution cleanup=complete")
endfunction

// MCP function: HTW_Test_RunRuntimeSmoke (module: tests.scenarios; tests/scenarios.j)
function HTW_Test_RunRuntimeSmoke takes nothing returns nothing
    call HTW_Test_AssertBoolean(HTW_Round >= 1, "fresh_initialization")
    call HTW_Test_AssertBoolean(HTW_Wave >= 1, "preparation_combat_resolution")
    call HTW_Test_AssertBoolean(HTW_RoutingLocked, "route_locked_during_wave")
endfunction

// MCP function: HTW_MCP_MainModule (module: main; main.j)
function HTW_MCP_MainModule takes nothing returns nothing
endfunction

function HTW_MCP_InitializeVariables takes nothing returns nothing
    set HTW_AdditionalWipeCost = 2
    set HTW_AliveHeroCount = 0
    set HTW_Bootstrapped = false
    set HTW_CombatSeconds = 90
    set HTW_HeroSelectionComplete = false
    set HTW_HeroSelectionSeconds = 60
    set HTW_InterestGold = 10
    set HTW_LastResolvedWave = 0
    set HTW_MatchOver = false
    set HTW_Phase = 0
    set HTW_PreparationSeconds = 35
    set HTW_ResolutionApplied = false
    set HTW_Round = 0
    set HTW_SendCursor = 1
    set HTW_SingleDeathCost = 1
    set HTW_StartingLives = 15
    set HTW_TerminalState = 0
    set HTW_TransitionGuard = false
    set HTW_Wave = 0
    set HTW_WaveActive = false
    set HTW_WaveReward = 50
    set HTW_Region_region_0 = CreateRegion()
    call RegionAddRect(HTW_Region_region_0, Rect(1152., -3072., 2496., -448.))
    set HTW_Region_region_1 = CreateRegion()
    call RegionAddRect(HTW_Region_region_1, Rect(-2464., -64., -320., 2240.))
    set HTW_Region_region_2 = CreateRegion()
    call RegionAddRect(HTW_Region_region_2, Rect(-256., 544., 320., 2112.))
    set HTW_Region_region_3 = CreateRegion()
    call RegionAddRect(HTW_Region_region_3, Rect(2528., -3040., 2944., -576.))
    set HTW_Region_region_4 = CreateRegion()
    call RegionAddRect(HTW_Region_region_4, Rect(-2880., 288., -2624., 1952.))
    set HTW_Region_region_5 = CreateRegion()
    call RegionAddRect(HTW_Region_region_5, Rect(320., -2848., 960., -1504.))
    set HTW_Region_region_6 = CreateRegion()
    call RegionAddRect(HTW_Region_region_6, Rect(-1888., 2240., -992., 2560.))
    set HTW_Region_region_7 = CreateRegion()
    call RegionAddRect(HTW_Region_region_7, Rect(-960., 2272., -64., 2592.))
    set HTW_Region_region_8 = CreateRegion()
    call RegionAddRect(HTW_Region_region_8, Rect(1248., -512., 2144., -192.))
    set HTW_Region_region_9 = CreateRegion()
    call RegionAddRect(HTW_Region_region_9, Rect(2176., -480., 3072., -160.))
endfunction

function HTW_Trigger_hero_death takes nothing returns nothing
    if not (true) then
        return
    endif
    call HTW_Heroes_OnDeath()
endfunction

function HTW_Trigger_map_init takes nothing returns nothing
    if not (true) then
        return
    endif
    call HTW_Heroes_Initialize()
    call HTW_HeroSelection_Begin()
endfunction

function HTW_Trigger_round_start takes nothing returns nothing
    if not (true) then
        return
    endif
    call HTW_Information_Display()
endfunction

function HTW_Trigger_runtime_tick takes nothing returns nothing
    if not (true) then
        return
    endif
    call HTW_Phases_Tick()
    call HTW_Sending_ProcessQueues()
endfunction

function HTW_Trigger_wave_resolved takes nothing returns nothing
    if not (true) then
        return
    endif
    call HTW_Information_Display()
    call HTW_Waves_Prepare()
endfunction

function HTW_MCP_RegisterTriggers takes nothing returns nothing
    local trigger htw_trigger
    set htw_trigger = CreateTrigger()
    call TriggerAddAction(htw_trigger, function HTW_Trigger_hero_death)
    call TriggerRegisterAnyUnitEventBJ(htw_trigger, EVENT_PLAYER_UNIT_DEATH)
    set htw_trigger = CreateTrigger()
    call TriggerAddAction(htw_trigger, function HTW_Trigger_round_start)
    call TriggerRegisterVariableEvent(htw_trigger, "HTW_Event_round_start", EQUAL, 1.0)
    call TimerStart(CreateTimer(), 1., true, function HTW_Trigger_runtime_tick)
    set htw_trigger = CreateTrigger()
    call TriggerAddAction(htw_trigger, function HTW_Trigger_wave_resolved)
    call TriggerRegisterVariableEvent(htw_trigger, "HTW_Event_wave_resolved", EQUAL, 1.0)
endfunction

function HTW_MCP_RunInitializationTriggers takes nothing returns nothing
    call HTW_Trigger_map_init()
endfunction

function main takes nothing returns nothing
    call SetCameraBounds(-3328. + GetCameraMargin(CAMERA_MARGIN_LEFT), -3584. + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 3328. - GetCameraMargin(CAMERA_MARGIN_RIGHT), 3072. - GetCameraMargin(CAMERA_MARGIN_TOP), -3328. + GetCameraMargin(CAMERA_MARGIN_LEFT), 3072. - GetCameraMargin(CAMERA_MARGIN_TOP), 3328. - GetCameraMargin(CAMERA_MARGIN_RIGHT), -3584. + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    call SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
    call NewSoundEnvironment("Default")
    call SetAmbientDaySound("IceCrownDay")
    call SetAmbientNightSound("IceCrownNight")
    call SetMapMusic("Music", true, 0)
    call InitBlizzard()
    call HTW_MCP_InitializeVariables()
    call HTW_MCP_Bootstrap()
    call HTW_MCP_RegisterTriggers()
    call HTW_MCP_RunInitializationTriggers()
endfunction

// Map Configuration
function config takes nothing returns nothing
    call SetMapName("Hero Team Wars - Two Arena MVP")
    call SetMapDescription("Nondescript")
    call SetPlayers(4)
    call SetTeams(4)
    call SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)

    // Player 1
    call DefineStartLocation(0, -1856., 1728.)
    // Player 2
    call DefineStartLocation(1, -640., 1856.)
    // Player 3
    call DefineStartLocation(2, 1664., -960.)
    // Player 4
    call DefineStartLocation(3, 2240., -960.)

    // Player setup
    call SetPlayerStartLocation(Player(0), 0)
    call ForcePlayerStartLocation(Player(0), 0)
    call SetPlayerColor(Player(0), ConvertPlayerColor(0))
    call SetPlayerRacePreference(Player(0), RACE_PREF_NIGHTELF)
    call SetPlayerRaceSelectable(Player(0), false)
    call SetPlayerController(Player(0), MAP_CONTROL_USER)
    call SetPlayerStartLocation(Player(1), 1)
    call ForcePlayerStartLocation(Player(1), 1)
    call SetPlayerColor(Player(1), ConvertPlayerColor(1))
    call SetPlayerRacePreference(Player(1), RACE_PREF_NIGHTELF)
    call SetPlayerRaceSelectable(Player(1), false)
    call SetPlayerController(Player(1), MAP_CONTROL_USER)
    call SetPlayerStartLocation(Player(2), 2)
    call ForcePlayerStartLocation(Player(2), 2)
    call SetPlayerColor(Player(2), ConvertPlayerColor(2))
    call SetPlayerRacePreference(Player(2), RACE_PREF_NIGHTELF)
    call SetPlayerRaceSelectable(Player(2), false)
    call SetPlayerController(Player(2), MAP_CONTROL_USER)
    call SetPlayerStartLocation(Player(3), 3)
    call ForcePlayerStartLocation(Player(3), 3)
    call SetPlayerColor(Player(3), ConvertPlayerColor(3))
    call SetPlayerRacePreference(Player(3), RACE_PREF_NIGHTELF)
    call SetPlayerRaceSelectable(Player(3), false)
    call SetPlayerController(Player(3), MAP_CONTROL_USER)

    // Team setup
    call SetPlayerTeam(Player(0), 0)
    call SetPlayerTeam(Player(1), 0)
    call SetPlayerTeam(Player(2), 1)
    call SetPlayerTeam(Player(3), 1)
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(3), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(3), true)
    call SetPlayerAllianceStateAllyBJ(Player(3), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(3), Player(2), true)

    // Ally priorities
    call SetStartLocPrioCount(0, 1)
    call SetStartLocPrio(0, 0, 1, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrioCount(1, 1)
    call SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrioCount(2, 1)
    call SetStartLocPrio(2, 0, 3, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrioCount(3, 1)
    call SetStartLocPrio(3, 0, 2, MAP_LOC_PRIO_HIGH)
endfunction
